// <auto-generated />
using Beltek66.HelloMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beltek66.HelloMvc.Migrations
{
    [DbContext(typeof(OkulDbContext))]
    [Migration("20220629115537_yenidendüzenlendi")]
    partial class yenidendüzenlendi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DersAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DersId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("Yas")
                        .HasColumnType("tinyint");

                    b.HasKey("OgrenciId");

                    b.HasIndex("SinifId");

                    b.ToTable("tblOgrenciler");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Ogretmen", b =>
                {
                    b.Property<int>("OgretmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("Yas")
                        .HasColumnType("tinyint");

                    b.HasKey("OgretmenId");

                    b.ToTable("tblOgretmenler");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.OgretmenDers", b =>
                {
                    b.Property<int>("OgretmenDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.HasKey("OgretmenDersId");

                    b.HasIndex("DersId");

                    b.HasIndex("OgretmenId");

                    b.ToTable("OgretmenDers");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Sinif", b =>
                {
                    b.Property<int>("SinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SinifAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinifId");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Ogrenci", b =>
                {
                    b.HasOne("Beltek66.HelloMvc.Models.Sinif", "Sinifi")
                        .WithMany("Ogenciler")
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinifi");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.OgretmenDers", b =>
                {
                    b.HasOne("Beltek66.HelloMvc.Models.Ders", "Ders")
                        .WithMany("OgretmenDers")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beltek66.HelloMvc.Models.Ogretmen", "Ogretmen")
                        .WithMany("OgretmenDers")
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Ders", b =>
                {
                    b.Navigation("OgretmenDers");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Ogretmen", b =>
                {
                    b.Navigation("OgretmenDers");
                });

            modelBuilder.Entity("Beltek66.HelloMvc.Models.Sinif", b =>
                {
                    b.Navigation("Ogenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
